---
apiVersion: v1
kind: Service
metadata:
  name: request-baskets
  labels:
    app: request-baskets
spec:
  ports:
    - name: http
      port: 55555
  selector:
    app: request-baskets
    tier: frontend
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  labels:
    app: request-baskets
  name: request-baskets
spec:
  host: request-baskets
  service:
    name: request-baskets
    port: 55555
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET", "PUT", "POST", "HEAD", "PATCH", "DELETE"]
      accessStrategies:
        - handler: noop
      mutators:
        - handler: noop
---
apiVersion: v1
kind: Secret
metadata:
  name: request-baskets-secret
type: opaque
stringData:
  VCAP_SERVICES: >
    {          
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-baskets
  labels:
    app: request-baskets
spec:
  selector:
    matchLabels:
      app: request-baskets
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: request-baskets
        tier: frontend
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: darklynx/request-baskets
          name: request-baskets
          imagePullPolicy: "Always"
          ports:
            - containerPort: 55555
              name: http
